import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import { Hero } from "./components/hero";

const inter = Inter({subsets:['latin']})

export const metadata: Metadata = {
  title: "NextJS WordPress GraphQl ",
  description: "Generated by Wahaj",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}>
          <div className="max-w-[780px] p-4 md:p-10 mx-auto min-h-screen bg-white">
            <Header />
            {children}
            <Footer />
          </div>
      </body>
    </html>
  );
}
